### ISSUE TITLE
"Convert a project" inhancements

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#26]
I tested the convert a project:
1- It hanged for a long time, then showed a massage that sdk like projects can only converted. Then a message that 48 files are converted. When I tried with class libraries, worked fine.
2- open the output folder after finishing.
3- clear text boxes after finishing, because they show contents of last file.
4- The bottom textboxs that show file names, can be 2 list boxes, so we can double click on any item to view its content in both languages. and keep the two list sync: always select the same index in both.
5- any non cs files, copy them to the output. I tried a project with cshtml files, but they are missing from the converted project.
6- the project file is missing too. Just copy the project file and change its extension from .csprog to ,vbprog. In the file content, Replace any ".cs" in the end of any word (to ignore .cshtml files) to ".vb".
7- I can select the text while it is converted. For safety, make textbox readonly while converting.
show percentage and elapsed time somewhere (at the window title bar for example).
8- While converting, I opened the file menu and clicked the convert project. The file dialog appeared. This can make a mess. Disable un wanted menus while converting, and add a cancel command ot a cancel button with keyboard shortcut (like escape) with a confirm msg box.
9- I also suggest to add a `Convert a solution` command. If the UI is interactive and the user can cancel, so no fear of large solutions.

**Comment by paul1956** [comment]
1. need more information, is there an open source project that is doing this? The long delay is caused by Buildalyzer and I have no control over it but could put up a message. #27 #28 
2. #29 
3. #30 
4, Good idea, I do that for errors on the right but using a list would be easier. #31 
5. I do if they are listed as content in project file, if they are not in project file I ignore. If you have another idea, enter a new issue.
6. I do this, not sure why you are not seeing this. I think you may be trying to convert a non-SDK project and I am not exiting properly since using Buildalyzer I can do a partial convert that is the same as folder convert.
7 I will fix. #33
7A I do for folder convert #34
8 Bug I thought I fixed yesterday, I will check again. #32
9 Planned I needed to refactor convert project first. #35

**Comment by VBAndCs** [comment]
> I do if they are listed as content in project file, if they are not in project file I ignore. If you have another idea, enter a new issue.

Project files don't have to list files anymore, except NuGets and references, and you may see excluded files only. By default, the project contains all files in the its folder and sub folders.
So, while scanning folders for .cs files, copy other files also to the output folder.
